### ISSUE TITLE
Requesting access to your repo

### ISSUE THREAD

**Issue by ratnanil** [mariottomarina/cma-week2#1]
Hi! Marina<br/><br/> Thank you for submitting the URL to your repo on moodle. After the submission deadline has passed (which will be this Thursday), we would like to give you feedback on your submission of this exercise (E2). For this reason, it would be great if you could give us (Nils `ratnanil` and Nikos `KimboGilda `) access to your repo. This will allow us to make changes to your code and push them to your repo.<br/><br/>Learn how to give us access [here](https://stackoverflow.com/a/55135314/4139249) or simply have a look at this gif: ![](https://i.stack.imgur.com/QRVQI.gif)<br/><br/> Grating us access is optional, we can also simply provide feedback using `issues` and `inline comments`. However, we recommend giving us access since it's a good exercise to work with collaborators (a skill that might come in handy during the project work). For experienced Github users, we can also work with `pull requests`. Please reply to this issue with the option you choose: <br/><br/>1. Grant us access (recommended)<br/>2. Grant no access, feedback via comments only <br> 3. Grant no access, feedback via pull request (only for git-enthusiasts) <br/><br/> You can close this issue afterwards.

**Comment by mariottomarina** [comment]
Hi Nils, I just gave you and Nikos acces to the repo of the exercise 2.
I hope it worked. :)
